server:
  port: 9091

jwt:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2knCj1Z9hhZ3IG731khVDTRFGc2utUpG+WpIfCjPFxqGejvkI+hdSeqyQn2ANKgjRP0rtz5wvZRpf/YdoJ37E8Bz0I3cjTfM6DwkONxPB+5g6NPsUYL33x+H87g1Pu7rs3bfTFexogiyMzzW1f6Rr1N+EPx43n7B8WHhtTfJbMhuKVh5OKR4b4QDMYzhpDkfaxX/WEsmcEkCIHqN8ZKkmeFayExEPI4NvsSSqq43fFmVI/NspATkwrE+fFBNc9wapiUDFEGrdQi+3hg89C+3KQatpa18MLF60IEFkWQAqVjFAzGXmBFhMp9hv/7l0Dp861Azq0Ea+j1bW9jCXuuIUQIDAQAB
