server:
  port: 9090

jwt:
  publicKey: >-
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2knCj1Z9hhZ3IG731khV
    DTRFGc2utUpG+WpIfCjPFxqGejvkI+hdSeqyQn2ANKgjRP0rtz5wvZRpf/YdoJ37
    E8Bz0I3cjTfM6DwkONxPB+5g6NPsUYL33x+H87g1Pu7rs3bfTFexogiyMzzW1f6R
    r1N+EPx43n7B8WHhtTfJbMhuKVh5OKR4b4QDMYzhpDkfaxX/WEsmcEkCIHqN8ZKk
    meFayExEPI4NvsSSqq43fFmVI/NspATkwrE+fFBNc9wapiUDFEGrdQi+3hg89C+3
    KQatpa18MLF60IEFkWQAqVjFAzGXmBFhMp9hv/7l0Dp861Azq0Ea+j1bW9jCXuuI
    UQIDAQAB
    -----END PUBLIC KEY-----
