spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    yamsroun.ssiach6: debug
    org.springframework:
      jdbc: debug
    org.hibernate:
      type:
        descriptor:
          sql: trace
