spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:ssia
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework:
      jdbc: DEBUG
      security: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    log4jdbc:
      audit: WARN
      sqltiming: DEBUG
      resultsettable: DEBUG
      connection: ERROR
      resultset: WARN
      sqlonly: WARN
