spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/Study/h2/db/security
    username: sa
    password:

logging:
  level:
    org.springframework:
      jdbc: DEBUG
      security: DEBUG
