server:
  port: 9090

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
    client:
      client-id: resourceserver
      client-secret: resourceserversecret
